branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/
 - enable-appveyor

environment:

  global:
    PIP_CACHE_DIR: "pip_cache"
    PIP_DISABLE_PIP_VERSION_CHECK: "yes"

  matrix:
    # Python 3.6, 64-bit
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 1

    # Python 3.6, 32-bit
    - TOXENV: "py36"
      TOX_APPVEYOR_X64: 0

matrix:
  fast_finish: true

clone_depth: 2

init:
  - git config --global user.email "cobrapy-bot@opencobra.com"
  - git config --global user.name "cobrapy-bot"
  - "ECHO %PYTHON%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V

cache:
  - pip_cache -> appveyor.yml

install:
  - "py -3.6 -m pip install pip setuptools wheel tox tox-appveyor"

build: off

test_script:
  - "py -3.6 -m tox"
