branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/
 - enable-appveyor

environment:

  global:
    PIP_CACHE_DIR: "pip_cache"
    PIP_DISABLE_PIP_VERSION_CHECK: "yes"

  matrix:

    - PYTHON: "C:\\Python27-x64"
      TOXENV: py27

    - PYTHON: "C:\\Python35-x64"
      TOXENV: py35

    - PYTHON: "C:\\Python36-x64"
      TOXENV: py36

matrix:
  fast_finish: true

clone_depth: 2

init:
  - "ECHO %PYTHON%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V

cache:
    - pip_cache -> appveyor.yml

install:
  - ps: pip install --user --upgrade pip setuptools wheel tox

build: off

test_script:
  - ps: tox
