branches:
 only:
 - master
 - devel
 - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/
 - enable-appveyor

environment:

  global:
    PIP_CACHE_DIR: "pip_cache"
    PIP_DISABLE_PIP_VERSION_CHECK: "yes"

  matrix:
    # Python 2.7, 64-bit
    - TOXENV: "py27"
      TOX_APPVEYOR_X64=1

    # Python 2.7, 32-bit
    - TOXENV: "py27"
      TOX_APPVEYOR_X64=0

    # Python 3.5, 64-bit
    - TOXENV: "py35"
      TOX_APPVEYOR_X64=1

    # Python 3.5, 32-bit
    - TOXENV: "py36"
      TOX_APPVEYOR_X64=0

    # Python 3.7, 64-bit
    - TOXENV: "py36"
      TOX_APPVEYOR_X64=1

    # Python 3.7, 32-bit
    - TOXENV: "py36"
      TOX_APPVEYOR_X64=0

matrix:
  fast_finish: true

clone_depth: 2

init:
  - "ECHO %PYTHON%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V

cache:
    - pip_cache -> appveyor.yml

install:
  - "build.cmd py -3.6 -m pip install pip setuptools wheel tox tox-appveyor"

build: off

test_script:
  - "build.cmd py -3.6 -m tox"
